cookie:
  expiry_days: 14
  key: kV4LwAVK24jzNnkBLNi1NcjDuGcAtvzcajEH2Np9bhLiC5eb7R1zxot53FPMJ3J
  name: StreamlitCookie
credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      failed_login_attempts: 0 # Will be managed automatically
      first_name: John
      last_name: Smith
      logged_in: False # Will be managed automatically
      password: abc # Will be hashed automatically
      roles: # Optional
      - admin
      - editor
      - viewer